// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID        int        `json:"id"`
	Post      int        `json:"post"`
	Content   string     `json:"content"`
	Author    string     `json:"author"`
	CreatedAt time.Time  `json:"createdAt"`
	Answers   int        `json:"answers"`
	Replies   []*Comment `json:"replies,omitempty"`
	ReplyTo   *int       `json:"replyTo,omitempty"`
}

type InputComment struct {
	Author  string `json:"author"`
	Content string `json:"content"`
	Post    int    `json:"post"`
	ReplyTo *int   `json:"replyTo,omitempty"`
}

type InputPost struct {
	Title           string `json:"title"`
	Content         string `json:"content"`
	Author          string `json:"author"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type Mutation struct {
}

type Post struct {
	ID              int       `json:"id"`
	Title           string    `json:"title"`
	Content         string    `json:"content"`
	Author          string    `json:"author"`
	CreatedAt       time.Time `json:"createdAt"`
	CommentsAllowed bool      `json:"commentsAllowed"`
}

type Query struct {
}

type Subscription struct {
}
